//Autogenerated file for LED and IR sensor mapping - DO NOT EDIT MANUALLY
extern const int lednobyxy[28][7];
extern const int ledxbyno[200];
extern const int ledybyno[200];
extern const int IRaddr[32];
extern const int IRreg[32];
